version: '3'
services:
  config:
    image: whtmdgus56/ibas-config:config
    container_name: backend-cloud-config
    networks:
      ibas-network:
        ipv4_address: 172.18.0.4
    ports:
      - "8888:8888"
    entrypoint: [ "java", "-jar", "app.jar" ]

  prod1:
    image: whtmdgus56/ibas-config:prod
    container_name: backend-prod1
    networks:
      ibas-network:
        ipv4_address: 172.18.0.2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod1
    entrypoint: ["java", "-jar", "app.jar", "--spring.profiles.active=prod1"]

  prod2:
    image: whtmdgus56/ibas-config:prod
    container_name: backend-prod2
    networks:
      ibas-network:
        ipv4_address: 172.18.0.2
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod2
    entrypoint: ["java", "-jar", "app.jar", "--spring.profiles.active=prod2"]

  dev1:
    image: whtmdgus56/ibas-config:dev
    container_name: backend-dev1
    networks:
      ibas-network:
        ipv4_address: 172.18.0.3
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev1
    entrypoint: ["java", "-jar", "app.jar", "--spring.profiles.active=dev1"]

  dev2:
    image: whtmdgus56/ibas-config:dev
    container_name: backend-dev2
    networks:
      ibas-network:
        ipv4_address: 172.18.0.3
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev2
    entrypoint: ["java", "-jar", "app.jar", "--spring.profiles.active=dev2"]


networks:
  ibas-network:
    external: true